### ISSUE TITLE
Never recovers from "server ping timeout", but restarting recovers it

### ISSUE THREAD

**Issue by NoozAbooz** [colonelwatch/nonceMiner#10]
After a few hours of mining, all devices running it drop to 0 hashrate and no coins are earned in the dashboard either. It says "server ping timeout" in the output and it doesn't start back up. Restarting the app fixes it though.

**Comment by NoozAbooz** [comment]
*I think it might be related to #9

**Comment by colonelwatch** [comment]
We can't say for sure, but it is likely. You're also saying that it doesn't recover automatically.

**Comment by colonelwatch** [comment]
Restarting is dependent right now on the [server ping thread reporting success](https://github.com/colonelwatch/nonceMiner/blob/7c04bfcbe7e7be8140ff2015ac5d496d4aafe269/src/nonceMiner.c#L162). This was something I wrote months ago, but that's not really useful now that I look at it.

Taking away this condition should make restarting unconditional, and that will probably fix this issue. Other than that, I don't know how to reproduce this issue and verify that the fix works. So, I'll leave the issue open for anyone who wants to report the same bug.

**Comment by colonelwatch** [comment]
In that commit above, I accidentally increased the wait time from 2 seconds to 10 seconds. My bad, that's fixed now. The above comment still applies.

**Comment by NoozAbooz** [comment]
Not sure if this is related, but the only thing I see in terminal is `09:11:44  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0, server ping timeout` when I run 1.4.1.

**Comment by colonelwatch** [comment]
I don't know how recently you've noticed this, but on my side not even `nc server.duinocoin.com 2811` is getting through. There server is probably just down right now.

**Comment by NoozAbooz** [comment]
> I don't know how recently you've noticed this, but on my side not even `nc server.duinocoin.com 2811` is getting through. There server is probably just down right now.

Huh, It was up for a bit when I last checked with the dashboard but I guess the API went down again.

**Comment by NoozAbooz** [comment]
> I don't know how recently you've noticed this, but on my side not even `nc server.duinocoin.com 2811` is getting through. There server is probably just down right now.

Server is back up, I think they changed how stuff works because vanilla miner works fine but nonce timeouts
![image](https://user-images.githubusercontent.com/44128563/123582484-21172600-d79b-11eb-95cf-a1d1d97474a0.png)

**Comment by NoozAbooz** [comment]
I suppose this can be closed too thanks to new commits.
