### ISSUE TITLE
nonceMiner not connecting, but official miner connects

### ISSUE THREAD

**Issue by colonelwatch** [colonelwatch/nonceMiner#11]
> I don't know how recently you've noticed this, but on my side not even `nc server.duinocoin.com 2811` is getting through. There server is probably just down right now.

Server is back up, I think they changed how stuff works because vanilla miner works fine but nonce timeouts
![image](https://user-images.githubusercontent.com/44128563/123582484-21172600-d79b-11eb-95cf-a1d1d97474a0.png)

_Originally posted by @mobilegmYT in https://github.com/colonelwatch/nonceMiner/issues/10#issuecomment-869353947_

**Comment by colonelwatch** [comment]
I'd love to work on this right now, but I can't reproduce this at the moment because the official miner isn't connecting on my side still. If I were to guess, though, the port seems to have changed from 2811 to 2813 for some reason now (https://github.com/revoxhere/duino-coin/blob/master/PC_Miner.py#L763).

A port change is odd behavior though, so I'll wait and see if it flips back, if I need to switch to 2813, or if they'll make more changes.

**Comment by NoozAbooz** [comment]
Not sure if this is related but...
![IMG_20210702_073039.jpg](https://user-images.githubusercontent.com/44128563/124282040-98381b80-db07-11eb-9e8f-4565ec3b9fd0.jpg)

**Comment by colonelwatch** [comment]
Thanks for letting me know. It looks like they also disabled port 2811 and opened ports 2812 to 2816. For now, I'll just switch to 2814 because that is implied to be the next default now (https://github.com/revoxhere/duino-coin/blob/39c0a4dfe7da657c6d4e3e59b37c9623c0e6ed37/PC_Miner.py#L809).

**Comment by colonelwatch** [comment]
Okay, switching the port number gets the connections back up. However, I can't rightly say this issue is fixed yet. For some reason, after the first share is submitted, the server takes so long returning job requests that it triggers my timeouts. Strangely though, it responds very quickly if I just run the official minimal PC miner.

I think the culprit is this line that was introduced to the master server two days ago:
https://github.com/revoxhere/duino-coin/blob/a5d48938c9a93f8472a4191303dfb43245dfc386/Master_Server/Server.py#L1473
It can add more than ten seconds of delay to anything hashing fast, but add just a few seconds to anything running as fast as the official code. I suspect this forced waiting is triggering the timeouts.

For now, I'll add in an equal delay so that the timeouts don't trigger, since the server will not be ready again right away. However, this means CPU utilization will be hampered, so I would suggest running more threads that your CPU's cores to work around that.

**Comment by colonelwatch** [comment]
Now master works. That said, my hashrate-counting code wasn't designed for this so it overreports, and I can't rightly release a new version until I fix that.

Or maybe should I just advocate to have the delay removed? This code is expressly targeted at fast programs like nonceMiner, so my opinion would raise a conflict of interest. However, delaying everyone by at least a couple seconds will slow the entire network down. 

Other than that, I'm going to close this issue because it's resolved.
