### ISSUE TITLE
[Suggestion] Parse in info

### ISSUE THREAD

**Issue by NoozAbooz** [colonelwatch/nonceMiner#13]
It would be much easier and quicker to start nonceMiner if I could parse in all the required variables via command line arguments, like `./nonceMiner <duco username> <threads> <optionally miner alias>`

**Comment by colonelwatch** [comment]
Agreed. I'd like to follow the POSIX conventions for command-line arguments though.

**Comment by NoozAbooz** [comment]
I'm not an expert on POSIX command line-related stuff so I probably did something wrong there but yeah you get the idea.

**Comment by NoozAbooz** [comment]
Looks to be implemented now in 2.0
