### ISSUE TITLE
clBuildProgram failed

### ISSUE THREAD

**Issue by viktor02** [colonelwatch/nonceMiner#16]
```
PS E:\Programs\DuinoCoin\gpu_miner> .\nonceMiner.exe -u username -g
Initializing nonceMiner v2.1.0...
Configured with username 'username', identifier '', difficulty 'EXTREME', and 4 thread(s).
OpenCL flag detected, detecting GPUs...
Building source and kernel for GPU 0 (NVIDIA GeForce GTX 1080)...
<kernel>:595:18: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
    hash_private(buffer_ptr, length, outbuf);
                 ^~~~~~~~~~
<kernel>:505:1: note: passing argument to parameter 'pass' here
def_hash(hash_private, __private, __private)
^
<kernel>:404:50: note: expanded from macro 'def_hash'
static void funcName(passTag const unsigned int *pass, int pass_len, hashTag unsigned int* hash)   \
                                                 ^

clBuildProgram failed with error code -11
```

**Comment by colonelwatch** [comment]
Odd, the `generic` type seems to be a feature of OpenCL 2.0, but I could have sworn that I compiled with OpenCL 1.2.

**Comment by viktor02** [comment]
What could be the reason? I have already tried to build it myself (on your binary the same error), but this did not solve the problem.  I have cuda11, can this be the case?

**Comment by colonelwatch** [comment]
Yeah, it might be a Nvidia driver thing. I never saw this problem running a GTX 1060 in a Ubuntu server. Anyway, it might be simple to just do what it asks. I can't reproduce the problem myself, so can you substitute the duco_s1.cl file in the OpenCL folder with this?

[duco_s1.zip](https://github.com/colonelwatch/nonceMiner/files/6889130/duco_s1.zip)

**Comment by viktor02** [comment]
![изображение](https://user-images.githubusercontent.com/19672960/127238909-36ff1675-fd08-4524-bee4-d8bdf75fc7ee.png)
Yes, it works! 
ps. the error on the screenshot says that "The attempt to establish a connection was unsuccessful, because the desired response was not received from another computer within the required time, or an already established connection was terminated due to an incorrect response from an already connected computer." Such a mistake almost every new job.

**Comment by colonelwatch** [comment]
Great, I'll push out a patch right away. Regarding the error, that's usually a problem with the other end. It might go away on its own, or the server maintainer may have to deal with it.
