### ISSUE TITLE
Master server changed port and pulse-pool connection issues

### ISSUE THREAD

**Issue by viktor02** [colonelwatch/nonceMiner#19]
You have ping a port of the server, which, apparently, does not work. Because of this, it gets out the error that the ping cannot reach the server. 
[here list of ports on master server](https://github.com/revoxhere/duino-coin/blob/925090c7cbcbd9d27fa5950a802e08f07b7780c9/Master_Server/Server.py#L60)
Also, I know that it is strange, but after changing the port, my miner began to appear in the panel. 
Actually, for this, I went to look at the source code, but the problem apparently solved by itself. Perhaps it was a servers fail, or the ping really changed something.

**Comment by viktor02** [comment]
> Error receiving job: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
15:32:49 [gpu0] Restarted due to an unexpected error

After `git diff`, I realized that I removed OpenCL from the program name. I made three runs for 3 minutes if there is an OpenCL in the title, then the miner does not appear in the panel. This error also appeared. Without OpenCl there were no errors. I still doubt, but so. 

`len = sprintf(buf, "%ld,%d,%s,%s\n", nonce, local_hashrate, program_name, identifier);`
![изображение](https://user-images.githubusercontent.com/19672960/128511166-d37984de-c9c6-4e62-b45f-b9ef0b7dc6d1.png)

`len = sprintf(buf, "%ld,%d,%s OpenCL,%s\n", nonce, local_hashrate, program_name, identifier);`
![изображение](https://user-images.githubusercontent.com/19672960/128511108-2d4d2012-a59e-429f-8761-7d64dbf1f6cf.png)

**Comment by colonelwatch** [comment]
It appears that you're right about the port: looks like they shut down port 2814 recently.

~~About the GPU timeout error, stripping "OpenCL" from the program name doesn't seem to help on my side.~~
Nevermind, I didn't realize that the pinging also had to be fixed in order to resolve the timeouts.

**Comment by viktor02** [comment]
> About the GPU timeout error, stripping "OpenCL" from the program name doesn't seem to help on my side.

Is this error on your side exist or not? Maybe these are some of my problems

**Comment by colonelwatch** [comment]
Yeah, I'm also getting the timeouts, if that's what you're asking.

**Comment by colonelwatch** [comment]
Oh hey, if I connect to the master server instead, I don't need to override the program name or strip the "OpenCL" name. It might just be a bug in the pulse-pool's code. The master server also has proper difficulty scaling. As a result though, the difficulty goes so high that I get integer overflows.

That said, proper difficulty scaling also mean less profits.

**Comment by viktor02** [comment]
> 
> 
> Oh hey, if I connect to the master server instead, I don't need to override the program name or strip the "OpenCL" name. It might just be a bug in the pulse-pool's code. The master server also has proper difficulty scaling. As a result though, the difficulty goes so high that I get integer overflows.
> 
> That said, proper difficulty scaling also mean less profits.

Hmm, after my commit on the pulse server, I have no errors.
By the way, has the difficulty increased lately? At the time of my first issue, I had 200-300 megahashes on gtx1080, now only 40-120 megahashes 

Upd. Oops, errors appeared :)

**Comment by colonelwatch** [comment]
> By the way, has the difficulty increased lately? At the time of my first issue, I had 200-300 megahashes on gtx1080, now only 40-120 megahashes

It's kinda the opposite actually. Pulse-pool has a bug where it doesn't send jobs of a high enough difficulty, so the GPU often just finishes the job instantly then gets stuck waiting for the server to send a new one. This shows up in the hashrate counter as a reduced hashrate. If you want an idea of how fast your GPU could be if it wasn't for that, try compiling and running `benchmark`.

Anyway, I need to fix the integer overflow, then I'd just recommend connecting to the master server instead by adding the `-o server.duinocoin.com:2813` option.

**Comment by viktor02** [comment]
So, errors occur on the pulsepool and the connection is simply closed or int overflow on the main server 

![05648](https://user-images.githubusercontent.com/19672960/128602297-946c1a0d-8420-4af7-a66f-31ecb798d8e6.png)

![05649](https://user-images.githubusercontent.com/19672960/128602298-32049a80-4cdc-428b-addc-c69406cf4915.png)

**Comment by colonelwatch** [comment]
Okay, these commits should fix the integer overflows, but I've run into another problem. This never showed up before because GPUs were spending so much time waiting: the EXTREME difficulty has a hashrate limit of 1 GH/s. As a result, it rejects shares from a RTX 3070 and accepts shares from a GTX 1060. So, the duino-coin developers have to remove the limit before you can point your GTX 1080 at it.

Regarding pulse-pool, I think I've found something that works:
* Compile with "OpenCL" not added to the program name, as you say
* Run with the `-n` flag to override the original "nonceMiner" program name

```
PS C:\Users\knypn\Documents\PROJECTS\duino-coin_projects\nonceMiner\bin> ./nonceMiner -t 0 -g -u travelmode -n freeMiner
Initializing nonceMiner v2.1.2...
Configured with username 'travelmode', identifier '', difficulty 'EXTREME', and 0 thread(s).
Program name overrided to 'freeMiner'...
OpenCL flag detected, detecting GPUs...
Building source and kernel for GPU 0 (Intel(R) UHD Graphics 620)...
OpenCL configuration complete, will launch GPU threads after CPU threads.
Starting threads...
08:17:58 [gpu0] Connected to 149.91.88.18:6000 with response: 2.6
08:18:01 [ping] Warning pinging master server: Timed out or failed
08:18:02 [gpu0] New job from 149.91.88.18 with difficulty 950000
08:18:04 [gpu0] Share accepted, work-time 5.235 s
08:18:05 [gpu0] New job from 149.91.88.18 with difficulty 1761173
08:18:08 [gpu0] Share accepted, work-time 3.468 s

08:18:08 [rprt] Hashrate: 27.10 MH/s, Accepted 2, Rejected 0

08:18:09 [gpu0] New job from 149.91.88.18 with difficulty 1718550
08:18:10 [gpu0] Share accepted, work-time 2.829 s
```

However, releasing a version of nonceMiner like this would be pretty drastic. I'd rather just stop defaulting to pulse-pool altogether. It has a ton of problems, and it's closed-source so there's no way to push fixes very quickly.

**Comment by colonelwatch** [comment]
Alright, the hashrate limit has been removed on the master server, so GPUs can properly be pointed at it. Check this out!

```
colonelwatch@server-pc:~/PROJECTS/nonceMiner/bin$ ./nonceMiner -t 0 -g -o server.duinocoin.com:2813 -u travelmode
Initializing nonceMiner v2.1.2...
Configured with username 'travelmode', identifier '', difficulty 'EXTREME', and 0 thread(s).
OpenCL flag detected, detecting GPUs...
Building source and kernel for GPU 0 (GeForce RTX 3070)...
Building source and kernel for GPU 1 (GeForce GTX 1060 6GB)...
OpenCL configuration complete, will launch GPU threads after CPU threads.
Starting threads...
19:12:30 [gpu0] Connected to server.duinocoin.com:2813 with response: 2.6
19:12:30 [gpu0] New job from server.duinocoin.com with difficulty 1500000
19:12:30 [gpu0] Share accepted, work-time 0.199 s
19:12:30 [gpu0] New job from server.duinocoin.com with difficulty 2981299
19:12:31 [gpu0] Share accepted, work-time 0.394 s
19:12:31 [gpu1] Connected to server.duinocoin.com:2813 with response: 2.6
19:12:31 [gpu0] New job from server.duinocoin.com with difficulty 5917280
19:12:31 [gpu1] New job from server.duinocoin.com with difficulty 1500000
19:12:31 [gpu0] Share accepted, work-time 0.543 s
19:12:31 [gpu1] Share accepted, work-time 0.289 s
```
```
19:12:44 [gpu0] New job from server.duinocoin.com with difficulty 239839845
19:12:46 [gpu1] Share accepted, work-time 7.907 s
19:12:46 [gpu1] New job from server.duinocoin.com with difficulty 115366530
19:12:48 [ping] Warning pinging master server: Timed out or failed
19:12:48 [gpu0] Share accepted, work-time 3.821 s
19:12:48 [gpu0] New job from server.duinocoin.com with difficulty 422522593
19:12:49 [gpu0] Share accepted, work-time 1.309 s
19:12:50 [gpu0] New job from server.duinocoin.com with difficulty 809969078

19:12:51 [rprt] Hashrate: 1752.05 MH/s, Accepted 4, Rejected 0

19:12:59 [gpu1] Share accepted, work-time 12.595 s
19:12:59 [gpu1] New job from server.duinocoin.com with difficulty 136176075
```

I'm going to stop defaulting to pulse-pool because I don't want to stop adding "OpenCL" from the program name just to mine with them. No longer adding "OpenCL" to the name would mean the miner is no longer marked as a GPU miner (see https://github.com/revoxhere/duino-coin/blob/9b1028a8bbb14f0f563f2563f5c66f462236bb0b/Master_Server/Server.py#L1898-L1901), and that wouldn't be very ethical. Instead, the master server actually works properly, though PC mining is only enabled on it temporarily if I remember correctly. I can't rightly default to either, so I'll drop defaulting altogether: users will have to choose the node themselves.

If they choose to connect to pulse-pool, they can refer to this issue so that they know they may need to compile with the "OpenCL" name not added. That is their own modification, and not the code of nonceMiner.

But all this is besides the original issue, the ping port change. I'll just accept part of pull request #20.

**Comment by viktor02** [comment]
> Check this out!
> Hashrate: 558.80 MH/s, Accepted 0, Rejected 0

Hah, my gtx1080 did not reach this limit :)

 > But all this is besides the original issue, the ping port change. I'll just accept part of pull request #20.

 Okay, thanks! Will I have to do something on my side?

**Comment by colonelwatch** [comment]
> Okay, thanks! Will I have to do something on my side?

Nope, I was able to modify the PR myself.
