### ISSUE TITLE
How can I limit the amount of GPU's used.

### ISSUE THREAD

**Issue by primitt** [colonelwatch/nonceMiner#23]
Hello, I have 2 GPUS (technically 1, but opencl is supported on my integrated graphics card) and I wanted to just use my dedicated one, how can I do that?

**Comment by colonelwatch** [comment]
At the moment, the '-g' option can only use all of the GPUs at once. Selecting GPUs would be a quick update I'd have to work on.

**Comment by primitt** [comment]
Could you? Cause like I kinda dont want to break my iGPU

**Comment by colonelwatch** [comment]
Yeah, and it sounds like a good update for the program.

**Comment by colonelwatch** [comment]
I think I have selecting devices working on the master branch now. Could you try it before I make a release?

**Comment by primitt** [comment]
> I think I have selecting devices working on the master branch now. Could you try it before I make a release?

Hello, Do I have to make the release?

**Comment by colonelwatch** [comment]
I think? What I mean exactly is that I'd like you compile the master branch and try selecting your dedicated GPU. It should be a command like `./nonceMiner -u <username here> -o <node here> -t 0 -g -s 1` to select GPU 1 and turn off CPU hashing. If you can't compile it though, that's alright, and I can compile it (in Windows) for you.

**Comment by primitt** [comment]
> I think? What I mean exactly is that I'd like you compile the master branch and try selecting your dedicated GPU. It should be a command like `./nonceMiner -u <username here> -o <node here> -t 0 -g -s 1` to select GPU 1 and turn off CPU hashing. If you can't compile it though, that's alright, and I can compile it (in Windows) for you.

Yeah, that's what I meant, ill try my best to compile it as I have minimal experience

**Comment by primitt** [comment]
> I think? What I mean exactly is that I'd like you compile the master branch and try selecting your dedicated GPU. It should be a command like `./nonceMiner -u <username here> -o <node here> -t 0 -g -s 1` to select GPU 1 and turn off CPU hashing. If you can't compile it though, that's alright, and I can compile it (in Windows) for you.

https://i.imgur.com/60uG6GK.png any idea why this happens?

**Comment by colonelwatch** [comment]
Have you installed the development OpenSSL binary? You can go to https://slproweb.com/products/Win32OpenSSL.html and download it (don't download the "Light" binary).

**Comment by primitt** [comment]
> Have you installed the development OpenSSL binary? You can go to https://slproweb.com/products/Win32OpenSSL.html and download it (don't download the "Light" binary).

Yes, I have installed it (not the light version), but ill reinstall it and see what happens.

**Comment by primitt** [comment]
> Have you installed the development OpenSSL binary? You can go to https://slproweb.com/products/Win32OpenSSL.html and download it (don't download the "Light" binary).

Even after reinstalling I get an error (same one), any idea why this is happening?

**Comment by primitt** [comment]
Also, I thought it was minggw but after installing i still got an error.

**Comment by primitt** [comment]
Same error btw

**Comment by colonelwatch** [comment]
Alright, nevermind then. 

[nonceMiner_windows.zip](https://github.com/colonelwatch/nonceMiner/files/7028372/nonceMiner_windows.zip)

The above file is pretty much the next release, compiled and ready to go.

Edit: I guess you're right that mingw should be the first thing to suspect, guess I missed that. Maybe the `bin` folder hasn't been added to your PATH yet? Then make wouldn't start either... I'm not sure what's going on there really.

**Comment by primitt** [comment]
Prolly, and idk how to add it to path, so yeah. Thanks for making the new release!!!!
