### ISSUE TITLE
MOST of the shares are rejected

### ISSUE THREAD

**Issue by djsawicko** [colonelwatch/nonceMiner#24]

**Comment by colonelwatch** [comment]
I just tried running nonceMiner with the command `./nonceMiner -u travelmode -o 149.91.88.18:6004 -g` (that was the pool provided by https://server.duinocoin.com/getPool at the time) and it worked fine with no rejected shares.

Under what conditions were the shares rejected? How did you run the program? Forgive me for being curt, but an empty description won't help me get to the bottom of anything.

**Comment by djsawicko** [comment]
> I just tried running nonceMiner with the command `./nonceMiner -u travelmode -o 149.91.88.18:6004 -g` (that was the pool provided by https://server.duinocoin.com/getPool at the time) and it worked fine with no rejected shares.
> 
> Under what conditions were the shares rejected? How did you run the program? Forgive me for being curt, but an empty description won't help me get to the bottom of anything.

Ummm so, i booted up my machine to find windows being an asshole and throwing inaccessible boot device, so i couldn't get the command, i do know that the pc or windows install isn't the issue because i tetsed it on another PC, I'll send my config later when I reinstall windows, i also used https://server.duinocoin.com/getPool. I'll try your config later since i don't have access to my machines, if i still get errors i can give you credantials so you can remote in with tight VNC... Thanks for responding....


BTW. I have a suggestion...
Add an option to disable CPU mining and keep openGL

**Comment by colonelwatch** [comment]
Damn, that's some fit your computer is throwing. I don't think I can just remote into your computer over the Internet, and I don't think I should either. However, I can check whether there's anything wrong with the config you provide or if there's actually a bug.

> Add an option to disable CPU mining and keep openGL

That's already possible if you call with `-t 0`, but only with the `-g` flag too (neither the CPU or GPU mining doesn't really make sense). I should've updated the documentation about that, so thanks for the reminder.

Also, it's OpenCL not OpenGL I'm using. SHA-1 definitely doesn't exist as a shader!

**Comment by djsawicko** [comment]
> I just tried running nonceMiner with the command `./nonceMiner -u travelmode -o 149.91.88.18:6004 -g` (that was the pool provided by https://server.duinocoin.com/getPool at the time) and it worked fine with no rejected shares.
> 
> Under what conditions were the shares rejected? How did you run the program? Forgive me for being curt, but an empty description won't help me get to the bottom of anything.

Ok, i installed windows on that laptop again, installed 1.1 openSSL instead of 3.x and used the net hashrate, and!!!!! Nothing, still a bunch of rejected shares😢

**Comment by djsawicko** [comment]
> > I just tried running nonceMiner with the command `./nonceMiner -u travelmode -o 149.91.88.18:6004 -g` (that was the pool provided by https://server.duinocoin.com/getPool at the time) and it worked fine with no rejected shares.
> > 
> > Under what conditions were the shares rejected? How did you run the program? Forgive me for being curt, but an empty description won't help me get to the bottom of anything.
> 
> Ok, i installed windows on that laptop again, installed 1.1 openSSL instead of 3.x and used the net hashrate, and!!!!! Nothing, still a bunch of rejected shares😢

Ummmmm, new news, extreme works fine.....
