### ISSUE TITLE
welp

### ISSUE THREAD

**Issue by TimyIsCool** [colonelwatch/nonceMiner#25]
![image](https://user-images.githubusercontent.com/74112751/132258506-4aa7a85d-edd8-48e6-9074-59874c0c4b81.png)

**Comment by djsawicko** [comment]
where the server is set you have to type 51.158.182.90:6006 instead of <51.158.182.90>:<6006> and the identifier should not have any spaces or unusual characters. and you forgot - where -a is. there is no need to specify threads too, it will autodetect.
If you want to mine with your IGPU you need a 4th gen processor too. 
 

How the command should look like:

`nonceminer.exe -u timy_g -a DUCO_S1 -i LOW -o 51.158.182.90:6006 -w 3200g -g`

-g is for OpenGL used for GPU mining

**Comment by TimyIsCool** [comment]
> where the server is set you have to type 51.158.182.90:6006 instead of <51.158.182.90>:<6006> and the identifier should not have any spaces or unusual characters. and you forgot - where -a is. there is no need to specify threads too, it will autodetect.
> If you want to mine with your IGPU you need a 4th gen processor too.
> 
> How the command should look like:
> 
> `nonceminer.exe -u timy_g -a DUCO_S1 -i LOW -o 51.158.182.90:6006 -w 3200g -g`
> 
> -g is for OpenGL used for GPU mining

tysm but im getting alot of rejected shares

![image](https://user-images.githubusercontent.com/74112751/132631049-c98b213e-6d44-4ebb-8b7d-758e9c7e117f.png)

**Comment by colonelwatch** [comment]
If you remove 	`-i LOW`, it'll work because LOW has hash-rate limits that the duino-coin devs strictly enforce. Everything up to and including `-i NET` is also like this (check the master server's code for what the limits are).

**Comment by TimyIsCool** [comment]
> If you remove `-i LOW`, it'll work because LOW has hash-rate limits that the duino-coin devs strictly enforce. Everything up to and including `-i NET` is also like this (check the master server's code for what the limits are).

tysm its working nicly now

**Comment by TimyIsCool** [comment]
im trying this on a diffrent pc and i have installed the cryptolib dll and now im getting error 0xc0150002

**Comment by colonelwatch** [comment]
> 0xc0150002

I've never seen that error before, but I've also never just moved the raw crypto dll around either. Have you tried installing OpenSSL yet? The link is in the README.

**Comment by TimyIsCool** [comment]
> > 0xc0150002
> 
> I've never seen that error before, but I've also never just moved the raw crypto dll around either. Have you tried installing OpenSSL yet? The link is in the README.

yes but i might of downloaded the light version

**Comment by TimyIsCool** [comment]
> > > 0xc0150002
> > 
> > 
> > I've never seen that error before, but I've also never just moved the raw crypto dll around either. Have you tried installing OpenSSL yet? The link is in the README.
> 
> yes but i might of downloaded the light version

i have now been banned for using my gpu tho i thought it was allowed

**Comment by colonelwatch** [comment]
Really? You're right though; it is allowed. Maybe it was some kind of mistake, but anyway I'm not the one to contact about that.

Was the 0xc0150002 issue solved though? I can close this issue if it was.

**Comment by djsawicko** [comment]
> im trying this on a diffrent pc and i have installed the cryptolib dll and now im getting error 0xc0150002

Install 1.1 instead of the newer 3.x version

**Comment by colonelwatch** [comment]
I wasn't aware of OpenSSL 3.0 as I was responding before. Installing OpenSSL 1.1.1 (from slproweb, since this was reported on Windows) is definitely the correct solution.
