### ISSUE TITLE
No work being done.

### ISSUE THREAD

**Issue by xscode** [colonelwatch/nonceMiner#7]
I tried both linux and windows releases also compiled myself on Ubuntu, all same result.

Initializing nonceMiner v1.3.0...
Enter username: 2E0BBN
Enter identifier ("None" for no identifier): laptop
Enter # of threads: 4
Starting threads...
14:03:00  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:02  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:04  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:06  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:08  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:10  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:12  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:14  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:16  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:18  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:20  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:22  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:24  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:26  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:28  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
14:03:30  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0

**Comment by colonelwatch** [comment]
Looks like Duino-coin's protocol got changed so that requesting the difficulty is a mandatory step now, should be an quick fix.
